server:
  port: 8000

#database configuration:mysql 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeedetails
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#hibernate configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL57Dialect
    